@startuml QosProfile_1.0.0-tsi.240104.1820+testsequence.1
skinparam responseMessageBelowArrow true

title
QosProfile_1.0.0-tsi.240104.1820+testsequence.1
end title

participant "Postman" as Postman
participant "Collection" as Collection
participant "../profile-collection" as ProfileCollection
participant "../qos-profile-capability" as Capability
participant "../qos-profile-configuration" as Configuration
participant "../createQosProfile" as CreateRpc
participant "../modifyQosProfile" as ModifyRpc
participant "../deleteQosProfile" as DeleteRpc

activate Postman

group Preparation
  Postman --\\o Collection : mountName

  Postman -> ProfileCollection
  Postman <-- ProfileCollection : {(uuid, profileName)}
  note right Postman
    filter for
    QosProfile
  end note
  Postman --\\o Collection : qosProfileUuid1
end

group Capability Validation
  Postman -> Capability
  Postman <-- Capability : {capabilites}
  note right Postman
    schema validation
  end note
  Postman --\\o Collection : capabilites
end

group Configuration Validation
  Postman -> Configuration
  Postman <-- Configuration : {configuration}
  note right Postman
    schema validation
  end note
  Postman --\\o Collection : configuration
end

group Create RPC
  Postman -> CreateRpc : {baseQosProfile=qosProfileUuid1}
  Postman <-- CreateRpc : {qosProfileUuid3}
  note right Postman
    schema validation
  end note
  Postman --\\o Collection : qosProfileUuid3
  Postman -> Configuration
  Postman <-- Configuration : {configuration}
  note right Postman
    configuration(qosProfileUuid3)==configuration(qosProfileUuid1)?
  end note
end

group Modify RPC
  Postman -> ModifyRpc : {qosProfileToBeModified=qosProfileUuid3, modifiedConfiguration}
  Postman --\\o Collection : modifiedConfiguration
  Postman <-- ModifyRpc : 204
  Postman -> Configuration
  Postman <-- Configuration : {configuration}
  note right Postman
    configuration(qosProfileUuid3)==modifiedConfiguration?
  end note
end

group Delete RPC
  Postman -> DeleteRpc : {obsoleteQosProfile=qosProfileUuid3}
  Postman <-- DeleteRpc : 204
end

deactivate Postman

@enduml